### PR TITLE
Small fix to make cuisine `file_write` usable on Mac OS.

### PR DESCRIPTION
**Pull request by ivanistheone**
There is a md5sum command and it works just like on linux.

### CODE REVIEW

**Comment by khenderick** [comment]
Unfortunately, this change breaks our code. We use the file_write(<filename>, <contents>) method to write a remote file. However, this file does not yet exists and thus needs to be created. It fails reporting the file does not exists.

This seems to be related to this change as ```0.7.5``` works fine.

A small test on a non-existing file on my local machine:

```
[kenneth@laptop ~]$ md5sum foobar | cut -d" " -f 1
md5sum: foobar: No such file or directory
[kenneth@laptop ~]$ $?
bash: 0: command not found
[kenneth@laptop ~]$ openssl md5 foobar
foobar: No such file or directory
[kenneth@laptop ~]$ $?
bash: 1: command not found
[kenneth@laptop ~]$ 
```

This difference in behavior might be the cause?

**Comment by sebastien** [comment]
Ouch... can you post the output of `uname -a`. I guess we'll have to support fallbacks for sigs.

**Comment by khenderick** [comment]
We're using vanilla ubuntu 14.04 machines.

```
root@ovs100:~# uname -a
Linux ovs100 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
root@ovs100:~# echo "HELLO" | openssl dgst -sha256
(stdin)= 3b09aeb6f5f5336beb205d7f720371bc927cd46c21922e334d47ba264acb5ba4
root@ovs100:~# 
```

**Comment by sebastien** [comment]
Ok then `0.7.7` will work for you

**Comment by khenderick** [comment]
It indeed works. Thanks.

**Pull request closed without merging**
